server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-json-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - regex:
          expression: 'REQ user="(?P<user>[^"]*)" method=(?P<method>\\S+) path="(?P<path>[^"]+)" status=(?P<status>\\d+) success=(?P<success>\\w+) duration_ms=(?P<duration_ms>\\d+)'
      - labels:
          user:
          method:
          path:
          status:
          success:
    relabel_configs:
      - source_labels: [__path__]
        regex: ".*/([0-9a-f]{12,64})/.*"
        target_label: container_id
